---

- name: FUEL | Pull remote database to local
  hosts: web
  user: "{{ fuel_deployment_user }}"
  vars_files:
    - vars/deployment_vars.yml
    - vars/deployment_vars_local.yml
  tasks:
    - include: tasks/db-pull-remote.yml

- name: FUEL | Put local database into Vagrant / localhost
  hosts: vagrant
  gather_info: no
  remote_user: vagrant
  vars_files:
    - vars/deployment_vars.yml
    - vars/deployment_vars_local.yml
  tasks:
    - include: tasks/db-pull-local.yml
