---

- name: FUEL | Get local database out of Vagrant / localhost
  sudo: no
  hosts: vagrant
  gather_facts: no
  remote_user: vagrant
  vars_files:
    - vars/deployment_vars.yml
    - vars/deployment_vars_local.yml
  tasks:
    - include: tasks/db-push-local.yml

- name: FUEL | Push local database to remote
  sudo: no
  hosts: web
  user: "{{ fuel_deployment_user }}"
  vars_files:
    - vars/deployment_vars.yml
    - vars/deployment_vars_local.yml
  tasks:
    - include: tasks/db-push-remote.yml
