---

- name: FUEL | Deploy application
  sudo: no
  user: "{{ fuel_deployment_user }}"
  hosts: web
  environment:
    TMPDIR: "{{ fuel_deployment_tmp_dir | default('/tmp') }}"
  vars:
    ansistrano_deploy_from: '{{ playbook_dir }}'
    ansistrano_keep_releases: 5
    ansistrano_deploy_via: 'git'
    ansistrano_version_dir: 'releases'
    ansistrano_current_dir: 'current'
    ansistrano_allow_anonymous_stats: no
    fuel_setup_project: true
    fuel_wpcli_source_url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    fuel_composer_source_url: https://getcomposer.org/composer.phar
    ansistrano_before_setup_tasks_file: "{{ playbook_dir }}/tasks/notify-before-setup.yml"
    ansistrano_after_setup_tasks_file: "{{ playbook_dir }}/tasks/setup.yml"
    ansistrano_after_update_code_tasks_file: "{{ playbook_dir }}/tasks/build.yml"
    ansistrano_before_symlink_shared_tasks_file: "{{ playbook_dir }}/tasks/symlink-setup.yml"
    ansistrano_before_cleanup_tasks_file: "{{ playbook_dir }}/tasks/hooks.yml"
    ansistrano_after_cleanup_tasks_file: "{{ playbook_dir }}/tasks/notify-after-cleanup.yml"
  vars_files:
    - vars/deployment_vars.yml
    - vars/deployment_vars_local.yml
  roles:
    - ansistrano.deploy
