---

- hosts: vagrant
  remote_user: vagrant
  become: true
  vars_files:
    - vars/deployment_vars.yml
    - vars/deployment_vars_local.yml
  tasks:
    - name: FUEL | Install unzip
      apt: pkg=unzip state=latest update_cache=yes

    - name: FUEL | Install MySQL client, server and related libraries
      apt: pkg={{ item }} state=latest
      with_items:
        - mysql-client
        - mysql-server
        - python-mysqldb

    - name: FUEL | Install PHP and its modules
      apt: pkg={{ item }} state=latest
      with_items:
        - php5
        - php5-cli
        - php5-curl
        - php5-gd
        - php5-imagick
        - php5-mysql
        - php5-xmlrpc

    - name: FUEL | Change PHP upload_max_filesize
      ini_file: dest=/etc/php5/apache2/php.ini
                section=PHP
                option=upload_max_filesize
                value=500M
                state=present
                backup=yes
                follow=yes

    - name: FUEL | Change PHP post_max_size
      ini_file: dest=/etc/php5/apache2/php.ini
                section=PHP
                option=post_max_size
                value=500M
                state=present
                backup=yes
                follow=yes

    - name: FUEL | Install Apache and its modules
      apt: pkg={{ item }} state=latest
      with_items:
        - apache2
        - libapache2-mod-php5

    - name: FUEL | Activate mod_rewrite
      apache2_module: name=rewrite state=present

    - name: FUEL | Start MySQL service
      service:
        name: "mysql"
        state: started
        enabled: yes

    - name: FUEL | Setup MySQL root password
      mysql_user:
        name: "root"
        password: "mysql"
        host: "{{ item }}"
        state: present
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: FUEL | Setup MySQL creds for root user
      template:
        src: "{{ mysqlTemplatePath }}"
        dest: "/root/.my.cnf"
        owner: "root"
        mode: 0600

    - name: FUEL | Delete blank MySQL users
      mysql_user:
        name: ""
        host: "{{ item }}"
        state: absent
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: FUEL | Drop MySQL test database
      mysql_db: name=test state=absent

    - name: FUEL | Setup empty database for WordPress
      mysql_db:
        name: "wordpress"
        encoding: "utf8"
        collation: "utf8_unicode_ci"
        state: "present"
        login_user: "root"
        login_password: "mysql"

    - name: FUEL | Setup MySQL user for WordPress
      mysql_user:
        name: "user_wp"
        password: "wordpress"
        host: "localhost"
        priv: "wordpress.*:ALL"
        state: "present"

    - name: FUEL | Put "vagrant" user in www-data group
      user:
        name: "vagrant"
        groups: "www-data"
        append: yes

    - name: FUEL | Symlink web root to unzipped WordPress
      file:
        src: "/vagrant"
        dest: "/var/www/site"
        state: "link"

    - name: FUEL | Copy virtual host setup over
      template: src={{ vhostTemplatePath }} dest=/etc/apache2/sites-available/

    - name: FUEL | Activate virtual host
      command: a2ensite vhost

    - name: FUEL | Deactivate default vhost
      command: a2dissite 000-default

    - name: FUEL | Ensure Apache is running
      service: name=apache2 state=restarted enabled=yes

    - name: FUEL | Install Composer
      get_url:
        url=https://getcomposer.org/composer.phar
        dest=/usr/bin/composer
        mode=0755

    - name: FUEL | Install WP-CLI
      get_url:
        url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest=/usr/bin/wp
        mode=0755
