---

- name: FUEL | Pull remote uploads to local
  user: "{{ fuel_deployment_user }}"
  hosts: web
  vars_files:
    - vars/deployment_vars.yml
    - vars/deployment_vars_local.yml
  tasks:
    - include: tasks/uploads-pull.yml
