---

- name: FUEL | Check for composer.json in project root or project_subtree_path
  stat:
    path: "{{ ansistrano_release_path.stdout }}/composer.json"
  register: composer_json
  when: fuel_setup_project

- name: FUEL | Fail if composer.json not found
  fail:
    msg: "Unable to find a `composer.json` file in the root of '{{ ansistrano_release_path.stdout }}'. Make sure your repo has a `composer.json` file in its root or edit `subtree_path` for '{{ site }}' in `wordpress_sites.yml` so it points to the directory with a `composer.json` file."
  when: fuel_setup_project and not composer_json.stat.exists

- name: FUEL | Install Composer dependencies
  command: "{{fuel_composer_dest}}/composer.phar install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader"
  environment:
    COMPOSER_AUTH: "{{ {'http-basic': {'repo.packagist.com': {'username': fuel_packagist_username, 'password': fuel_packagist_token}}} | to_json }}"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  when: fuel_setup_project

- name: FUEL | Check for composer.json in theme folder
  stat:
    path: "{{ ansistrano_release_path.stdout }}/web/app/themes/{{ fuel_theme_name }}/composer.json"
  register: theme_composer_json
  when: fuel_build_theme

- name: FUEL | Check if local theme deployment exists
  connection: local
  stat:
    path: "{{ fuel_local_site_path }}/web/app/themes/{{ fuel_theme_name }}/deployment.yml"
  register: theme_local_deployment
  when: fuel_build_theme

- name: FUEL | Install composer dependencies for theme
  command: "{{fuel_composer_dest}}/composer.phar install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader --auth http-basic.repo.packagist.com {{fuel_packagist_username}} {{fuel_packagist_token}}"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}/web/app/themes/{{ fuel_theme_name }}"
  when:
    - fuel_build_theme
    - theme_composer_json.stat.exists and not theme_local_deployment.stat.exists

- name: FUEL | Run npm install for theme
  command: npm install
  connection: local
  args:
    chdir: "{{ fuel_local_site_path }}/web/app/themes/{{ fuel_theme_name }}"
  when:
    - fuel_build_theme
    - not theme_local_deployment.stat.exists

- name: FUEL | Run bower install for theme
  command: bower install
  connection: local
  args:
    chdir: "{{ fuel_local_site_path }}/web/app/themes/{{ fuel_theme_name }}"
  when:
    - fuel_build_theme
    - not theme_local_deployment.stat.exists

- name: FUEL | Run gulp for theme
  command: gulp --production
  connection: local
  args:
    chdir: "{{ fuel_local_site_path }}/web/app/themes/{{ fuel_theme_name }}"
  when:
    - fuel_build_theme
    - not theme_local_deployment.stat.exists

- name: FUEL | Run local theme deployment
  include: "{{ fuel_local_site_path }}/web/app/themes/{{ fuel_theme_name }}/deployment.yml"
  when:
    - fuel_build_theme
    - theme_local_deployment.stat.exists

- name: FUEL | Copy project local files for theme
  synchronize:
    src: "{{ fuel_local_site_path }}/web/app/themes/{{ fuel_theme_name }}/dist"
    dest: "{{ ansistrano_release_path.stdout }}/web/app/themes/{{ fuel_theme_name }}"
    group: no
    owner: no
    rsync_opts: --chmod=Du=rwx,--chmod=Dg=rx,--chmod=Do=rx,--chmod=Fu=rw,--chmod=Fg=r,--chmod=Fo=r
  when: fuel_build_theme
