---

# Ensure symlinks source exists befor deleting target
- name: FUEL | Sync pulled database to Vagrant
  synchronize: src=/tmp/wpcli_database.sql dest=/tmp/wpcli_database.sql

- name: FUEL | Import database to local
  command: wp db import /tmp/wpcli_database.sql --debug chdir=/vagrant

- name: FUEL | Replace old domain with new
  command: wp search-replace {{fuel_remote_url}} {{fuel_local_url}} --skip-columns=guid --url={{fuel_remote_url}} --debug chdir=/vagrant
