---

- name: FUEL | Install Composer
  get_url:
    url: "{{ fuel_composer_source_url }}"
    dest: "{{ ansistrano_shared_path }}"
    mode: 0755

- name: FUEL | Install WP-CLI
  get_url:
    url: "{{ fuel_wpcli_source_url }}"
    dest: "{{ ansistrano_shared_path }}"
    mode: 0755
